<MyRoot>

    rand_aff: rand_aff

    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Random Affirmation"
            font_size: 64
            color: 1.15, 1.95, 1.08
        Label:
            id: rand_aff
            text: "_"
            font_size: 24
        Button:
            text: "Generate"
            font_size: 32
            size: 100, 50
            on_press: root.generate_affirmation()